apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: redis
          image: 
          ports:
            - containerPort: 5672
              name: redis
          env:
            - name: REDIS_URL
              value: "redisConnectionString"
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-front
  template:
    metadata:
      labels:
        app: weather-front
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: weather-front
          image: 
          ports:
            - containerPort: 8080
              name: weather-front
          env:
            - name: WEATHER_API_KEY
              value: 59aabf4168b36a217d609d8846397c35
          resources:
            requests:
              cpu: 1m
              memory: 200Mi
            limits:
              cpu: 1000m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: weather-front
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: weather-front
  type: LoadBalancer