name: Build & Push Remix Weather App Docker to ACR

on:
  pull_request:
    branches:
      - main
    paths: #paths to the weather app here
      - 'app/**'
      - 'routes/**'
      - 'public/**'
      - 'package.json'
      - 'remix.config.js'
      - 'Dockerfile'

jobs:
  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    env:
      ACR_LOGIN_SERVER: yourregistry.azurecr.io

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Azure Login to ACR
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure ACR Login
        run: |
          az acr login --name yourregistry

      - name: Build and Push Docker Image
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker build -t $ACR_LOGIN_SERVER/remix-weather-app:$IMAGE_TAG .
          docker push $ACR_LOGIN_SERVER/remix-weather-app:$IMAGE_TAG
