name: Build & Push Remix Weather App Docker to ACR

on:
  pull_request:
    branches:
      - main
    paths: #paths to the weather app here
      - 'app/**' # Only run when application code changes

#Special permissions required for OIDC authentication
permissions:
  id-token: write
  contents: read

defaults:
  run:
    working-directory: ./app/tf-app 
    
jobs:
  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Azure Login with OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Log in to Azure Container Registry (ACR)
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: 00000000-0000-0000-0000-000000000000  # Dummy (OIDC doesn't need this)
          password: dummy
          
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./app
          file: ./app/Dockerfile
          push: true
          tags: ${{ secrets.ACR_LOGIN_SERVER }}/weather-app:${{ github.sha }}
