name: Deploy Remix Weather App to AKS

on:
  pull_request:
    branches: [main]
    paths:
      - 'app/**'
      - '.github/workflows/**'
  push:
    branches: [main]
    paths:
      - 'app/**'
      - '.github/workflows/**'

env:
  TF_VERSION: '1.5.0'
  AZURE_RESOURCE_GROUP: 'your-aks-resource-group'
  AZURE_AKS_CLUSTER: 'your-aks-cluster-name'
  APP_DIR: './app'
  

jobs:
  deploy:
    name: Deploy to AKS
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ env.AZURE_RESOURCE_GROUP }}
          cluster-name: ${{ env.AZURE_AKS_CLUSTER }}

      - name: Terraform Init
        working-directory: terraform/
        run: terraform init

      - name: Terraform Apply
        working-directory: terraform/
        run: terraform apply -auto-approve
        env:
          TF_VAR_environment: ${{ github.event_name == 'push' && 'production' || 'test' }}

      - name: Deploy Application to AKS
        run: |
          kubectl apply -f k8s/${{ github.event_name == 'push' && 'production' || 'test' }}-deployment.yaml
        working-directory: ${{ env.APP_DIR }}

