name: Deploy Remix Weather App to AKS

on:
  pull_request:
    branches: [main]
    paths:
      - 'app/**'
      - '*.tsx'
      - '*.ts'
      - 'package*.json'
      - 'Dockerfile'
      - 'remix.config.js'
      - 'tsconfig.json'
      - 'k8s/**'
  push:
    branches: [main]
    paths:
      - 'app/**'
      - '*.tsx'
      - '*.ts'
      - 'package*.json'
      - 'Dockerfile'
      - 'remix.config.js'
      - 'tsconfig.json'
      - 'k8s/**'
      
permissions:
  id-token: write
  contents: read
  pull-requests: write

#These environment variables are used by the terraform azure provider to setup OIDC authenticate. 
env:
  ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID_RW }}"
  ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
  ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"
  ARM_ACCESS_KEY: "${{ secrets.ARM_ACCESS_KEY }}"
  # AKS cluster information
  AZURE_RESOURCE_GROUP: "cst8918-final-project-group-1-RG"
  AZURE_AKS_CLUSTER: "${{ github.event_name == 'push' && 'cst8918-final-project-group-1-aks-prod' || 'cst8918-final-project-group-1-aks-test' }}"
  ENVIRONMENT: "${{ github.event_name == 'push' && 'production' || 'test' }}"

defaults:
  run:
    working-directory: ./
  
jobs:
  deploy:
    name: Deploy to AKS
    runs-on: ubuntu-latest
    environment: ${{ github.event_name == 'push' && 'production' || 'test' }}
    # Wait for the build job to complete
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository)
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID_RW }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ env.AZURE_RESOURCE_GROUP }}
          cluster-name: ${{ env.AZURE_AKS_CLUSTER }}

      - name: Create K8s directory if it doesn't exist
        run: |
          mkdir -p k8s
          
      - name: Generate K8s deployment file
        run: |
          cat > k8s/${{ env.ENVIRONMENT }}-deployment.yaml << EOF
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: weather-app-${{ env.ENVIRONMENT }}
            labels:
              app: weather-app
              environment: ${{ env.ENVIRONMENT }}
          spec:
            replicas: ${{ github.event_name == 'push' && '3' || '1' }}
            selector:
              matchLabels:
                app: weather-app
                environment: ${{ env.ENVIRONMENT }}
            template:
              metadata:
                labels:
                  app: weather-app
                  environment: ${{ env.ENVIRONMENT }}
              spec:
                containers:
                - name: weather-app
                  image: ${{ secrets.ACR_LOGIN_SERVER }}/weather-app:${{ github.sha }}
                  ports:
                  - containerPort: 3000
                  env:
                  - name: WEATHER_API_KEY
                    value: "${{ secrets.WEATHER_API_KEY }}"
                  - name: REDIS_CONNECTION_STRING
                    value: "${{ secrets.REDIS_CONNECTION_STRING }}"
          ---
          apiVersion: v1
          kind: Service
          metadata:
            name: weather-app-service-${{ env.ENVIRONMENT }}
          spec:
            selector:
              app: weather-app
              environment: ${{ env.ENVIRONMENT }}
            ports:
            - port: 80
              targetPort: 3000
            type: LoadBalancer
          EOF

      - name: Deploy to AKS
        run: |
          kubectl apply -f k8s/${{ env.ENVIRONMENT }}-deployment.yaml
          echo "Deployed to ${{ env.ENVIRONMENT }} environment"
          
      - name: Comment on PR about deployment
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `✅ Application deployed to TEST environment`
            })

