name: Deploy Remix Weather App to AKS

on:
  workflow_run:
    workflows: ["Build & Push Remix Weather App Docker to ACR"]
    types:
      - completed

permissions:
  id-token: write
  contents: read
  pull-requests: write

#These environment variables are used by the terraform azure provider to setup OIDC authenticate. 
env:
  ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID_RW }}"
  ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
  ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"
  ARM_ACCESS_KEY: "${{ secrets.ARM_ACCESS_KEY }}"
  # AKS cluster information
  AZURE_RESOURCE_GROUP: "cst8918-final-project-group-1-RG"
  AZURE_AKS_CLUSTER: "${{ github.event.workflow_run.conclusion == 'success' && contains(github.event.workflow_run.head_branch, 'main') && 'cst8918-final-project-group-1-aks-prod' || 'cst8918-final-project-group-1-aks-test' }}"
  ENVIRONMENT: "${{ github.event.workflow_run.conclusion == 'success' && contains(github.event.workflow_run.head_branch, 'main') && 'production' || 'test' }}"

defaults:
  run:
    working-directory: ./
  
jobs:
  deploy:
    name: Deploy to AKS
    # Only run if the build workflow completed successfully
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    environment: ${{ contains(github.event.workflow_run.head_branch, 'main') && 'production' || 'test' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      # Get PR number for commenting
      - name: Get PR Number
        id: get-pr-number
        if: ${{ !contains(github.event.workflow_run.head_branch, 'main') }}
        run: |
          PR_INFO=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/commits/${{ github.event.workflow_run.head_sha }}/pulls")
          PR_NUMBER=$(echo "$PR_INFO" | jq -r '.[0].number')
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_OUTPUT

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID_RW }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ env.AZURE_RESOURCE_GROUP }}
          cluster-name: ${{ env.AZURE_AKS_CLUSTER }}

      - name: Create K8s directory if it doesn't exist
        run: |
          mkdir -p k8s
          
      - name: Generate K8s deployment file
        run: |
          cat > k8s/${{ env.ENVIRONMENT }}-deployment.yaml << EOF
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: weather-app-${{ env.ENVIRONMENT }}
            labels:
              app: weather-app
              environment: ${{ env.ENVIRONMENT }}
          spec:
            replicas: ${{ contains(github.event.workflow_run.head_branch, 'main') && '3' || '1' }}
            selector:
              matchLabels:
                app: weather-app
                environment: ${{ env.ENVIRONMENT }}
            template:
              metadata:
                labels:
                  app: weather-app
                  environment: ${{ env.ENVIRONMENT }}
              spec:
                containers:
                - name: weather-app
                  image: ${{ secrets.ACR_LOGIN_SERVER }}/weather-app:${{ github.event.workflow_run.head_sha }}
                  ports:
                  - containerPort: 3000
                  env:
                  - name: WEATHER_API_KEY
                    value: "${{ secrets.WEATHER_API_KEY }}"
                  - name: REDIS_CONNECTION_STRING
                    value: "${{ secrets.REDIS_CONNECTION_STRING }}"
          ---
          apiVersion: v1
          kind: Service
          metadata:
            name: weather-app-service-${{ env.ENVIRONMENT }}
          spec:
            selector:
              app: weather-app
              environment: ${{ env.ENVIRONMENT }}
            ports:
            - port: 80
              targetPort: 3000
            type: LoadBalancer
          EOF

      - name: Deploy to AKS
        run: |
          kubectl apply -f k8s/${{ env.ENVIRONMENT }}-deployment.yaml
          echo "Deployed to ${{ env.ENVIRONMENT }} environment"
          
      # Comment on PR
      - name: Comment on PR
        if: ${{ !contains(github.event.workflow_run.head_branch, 'main') && steps.get-pr-number.outputs.PR_NUMBER != '' }}
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = '${{ steps.get-pr-number.outputs.PR_NUMBER }}';
            github.rest.issues.createComment({
                issue_number: parseInt(prNumber),
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `✅ App deployed to ${{ env.ENVIRONMENT }} environment: \`${{ secrets.ACR_LOGIN_SERVER }}/weather-app:${{ github.event.workflow_run.head_sha }}\``
            })

