name: 'Terraform Static Analysis'

on:
  push:
    branches:
      - '**'  # Runs on push to any branch

defaults:
  run:
    working-directory: ./infra/tf-app

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  terraform-static-tests:
    name: 'Terraform Static Analysis'
    runs-on: ubuntu-latest
    
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

    # Install the latest version of Terraform CL
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    # Initialize Terraform 
    # The -backend=false flag is used to prevent Terraform from using the remote backend.
    - name: Terraform Init
      run: terraform init -backend=false

    # Validate terraform
    - name: Terraform Validate
      run: terraform validate

    # Checks that all Terraform configs adhere to format
    - name: Terraform Format
      run: terraform fmt -check -recursive

    # Perform a security scan of the terraform code tfsec
    - name: tfsec
      uses: tfsec/tfsec-sarif-action@master
      with:
        sarif_file: tfsec.sarif         

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v3
      with:
        # Path to SARIF file relative to the root of the repository
        sarif_file: tfsec.sarif